package com.xuzhipeng.wustlib.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xuzhipeng.wustlib.db.Book;
import com.xuzhipeng.wustlib.db.Comment;
import com.xuzhipeng.wustlib.db.Suggest;
import com.xuzhipeng.wustlib.db.User;
import com.xuzhipeng.wustlib.db.Collect;

import com.xuzhipeng.wustlib.db.BookDao;
import com.xuzhipeng.wustlib.db.CommentDao;
import com.xuzhipeng.wustlib.db.SuggestDao;
import com.xuzhipeng.wustlib.db.UserDao;
import com.xuzhipeng.wustlib.db.CollectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig suggestDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig collectDaoConfig;

    private final BookDao bookDao;
    private final CommentDao commentDao;
    private final SuggestDao suggestDao;
    private final UserDao userDao;
    private final CollectDao collectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        suggestDaoConfig = daoConfigMap.get(SuggestDao.class).clone();
        suggestDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        collectDaoConfig = daoConfigMap.get(CollectDao.class).clone();
        collectDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        suggestDao = new SuggestDao(suggestDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        collectDao = new CollectDao(collectDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(Comment.class, commentDao);
        registerDao(Suggest.class, suggestDao);
        registerDao(User.class, userDao);
        registerDao(Collect.class, collectDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        commentDaoConfig.clearIdentityScope();
        suggestDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        collectDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public SuggestDao getSuggestDao() {
        return suggestDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CollectDao getCollectDao() {
        return collectDao;
    }

}
